import { defineConfig } from '@playwright/test';

/**
 * Base Playwright configuration for the automation worker.
 * This is overridden per-execution with a dynamic config generated by the test runner.
 */
export default defineConfig({
  timeout: 60000,
  retries: 0,
  use: {
    headless: true,
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    video: 'off',
  },
  reporter: [['json', { outputFile: 'report.json' }]],
});
